# Generated by Django 4.0.5 on 2022-08-03 17:18

import autoslug.fields
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='titulo')),
                ('subtítulo', models.TextField(blank=True, max_length=70, null=True)),
                ('cuerpo', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('autor', models.CharField(max_length=20)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('imagen', models.ImageField(upload_to='media')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_perfil', models.ImageField(upload_to='media')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
