# Generated by Django 4.0.6 on 2022-07-30 23:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='imagen',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='subtítulo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
