# Generated by Django 4.0.5 on 2022-08-03 17:43

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='titulo'),
        ),
    ]
