# Generated by Django 4.0.5 on 2022-08-03 02:15

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogApp', '0002_blog_post_minicuerpo_alter_blog_post_cuerpo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_post',
            name='minicuerpo',
        ),
        migrations.AddField(
            model_name='blog_post',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='titulo'),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_perfil', models.ImageField(upload_to='media')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
