# Generated by Django 4.0.5 on 2022-08-03 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_remove_blog_post_minicuerpo_blog_post_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
