# Generated by Django 4.0.5 on 2022-08-03 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_remove_blog_post_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_post',
            old_name='subtítulo',
            new_name='subtitulo',
        ),
    ]
