# Generated by Django 4.0.5 on 2022-08-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0004_rename_subtítulo_blog_post_subtitulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='subtitulo',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
