# Generated by Django 4.0.5 on 2022-08-06 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0006_alter_blog_post_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogApp.autor'),
        ),
    ]
