# Generated by Django 4.0.5 on 2022-08-06 18:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0009_alter_blog_post_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
